version: '3.1'

networks:
  db_network:

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - 5432:${POSTGRES_PORT}
    networks:
      - db_network
  bot:
    build: .
    networks:
      - db_network
    depends_on: [database]
    # Only while developpment
    # volumes:
    # - ./src:/home/node/app/src
    # - ./prisma:/home/node/app/prisma
